server:
  port: 8102
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    username: usian
    password: usian
    virtual-host: /
    publisher-confirms: true #开启消息确认回调
    publisher-returns: true #开启消息退回回调

#订单
ORDER_ID_KEY: ORDER_ID_KEY
ORDER_ID_BEGIN: 100544
ORDER_ITEM_ID_KEY: ORDER_ITEM_ID_KEY

#商品详情
ITEM_INFO: ITEM_INFO
BASE: BASE
DESC: DESC
PARAM: PARAM
ITEM_INFO_EXPIRE: 86400

#配置缓存首页商品分类的 key
PROTAL_CATRESULT_KEY: PROTAL_CATRESULT_KEY

SETNX_BASC_LOCK_KEY: SETNX_BASC_LOCK_KEY
SETNX_DESC_LOCK_KEY: SETNX_DESC_LOCK_KEY
SETNX_PARAM_LOCK_KEY: SETNX_PARAM_LOCK_KEY