spring:
  application:
    name: usian-cart-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#购物车
CART_COOKIE_KEY: CART_COOKIE_KEY
CART_COOKIE_EXPIRE: 604800