spring:
  application:
    name: usian-portal-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
server:
  port: 8094
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/