spring:
  rabbitmq:
    host: 127.0.0.1
    username: usian
    password: usian
    virtual-host: /
  data:
    elasticsearch:
      cluster-nodes: 192.168.184.131:9200
  application:
    name: usian-search-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8095
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#索引名称
ES_INDEX_NAME: usian
#类型名称
ES_TYPE_NAME: item