spring:
  application:
    name: usian-search-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8096
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#全局配置
#请求连接的超时时间
ribbon:
  ConnectTimeout: 60000
  #请求处理的超时时间
  ReadTimeout: 60000